gitops:
  name: gitops-helm-application
  projectIdentifier: default_project
  orgIdentifier: default
  type: application
  application:
    metadata:
      namespace: default
      clusterName: gitops_cluster
    spec:
      source:
        repoURL: https://github.com/Stan-BK/harness-test.git
        path: .
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: default
  agentIdentifier: harnessagent
  clusterIdentifier: gitopscluster
  repoIdentifier: gitopsrepo